#!/bin/sh
hostname virt
uname -a
mkdir /dev/pts
mkdir /dev/shm
mount -a
mount -o rw,remount /
/sbin/syslogd
/sbin/klogd
/sbin/udhcpc -p /run/udhcpc.pid -C
/usr/sbin/ntpd -p pool.ntp.org
[ -f /usr/sbin/dropbear ] && /usr/sbin/dropbear -R -B
