#!/bin/sh
hostname virt
ip addr add 127.0.0.1/8 dev lo
mkdir /dev/pts
mkdir /dev/shm
mount -a
mount -o rw,remount / | logger -t mount
/sbin/syslogd
/sbin/klogd
/sbin/udhcpc -p /run/udhcpc.pid -C -S 2> /dev/null
/usr/sbin/ntpd -p pool.ntp.org
[ -f /usr/sbin/dropbear ] && /usr/sbin/dropbear -R -B
