name: Build
on:
  workflow_dispatch:
jobs:
  build-base:
    runs-on: ubuntu-24.04 #https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: linux
        key: cache-${{ hashFiles('linux.version') }}
    - run: ./build.sh && sudo ./buildImage.sh && tar czf virt.tar.gz vmlinuz vda.img
    - uses: actions/upload-artifact@v4
      with:
        name: virt
        path: virt.tar.gz
  build-tool:
    needs: build-base
    runs-on: macos-14 #https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
    steps:
    - uses: actions/checkout@v4
    - run: sudo xcode-select -s /Applications/Xcode_15.3.app
    - run: cd virt && xcodebuild -arch arm64
    - uses: actions/download-artifact@v4
      with:
        name: virt
        path: virt/build/Release
    - run: cd virt/build/Release && tar xf virt.tar.gz && tar czf virt.tar.gz virt vmlinuz vda.img
    - uses: actions/upload-artifact@v4
      with:
        name: virt
        path: virt/build/Release/virt.tar.gz
        overwrite: true
